### ISSUE TITLE
Tiny Snake not running on fresh delivered device.

### ISSUE THREAD

**Issue by RobertK66** [tinypico/tinypico-micropython#1]
I got my delivery and wanted to test out the play shield. After loading the files of the repository https://github.com/tinypico/tinypico-micropython/tree/master/play%20shield%20examples/tiny-snake I get this error:

````
File "ssd1306.py", line 109, in write_data
AttributeError: 'I2C' object has no attribute 'writevto'
MicroPython v1.10-231-g673db939b-dirty on 2019-03-31; ESP32 module with ESP32
````

### Workaround:
I manged to get it to work by replacing the lines 108,109 of the ssd1306.py file with its previous content from Commit cf9a2b58275134654843b9b81cc9154185a043ba :

````
def write_data(self, buf):	  
        self.temp[0] = self.addr << 1	     
        self.temp[1] = 0x40 
        self.i2c.start()	
        self.i2c.write(self.temp)	
        self.i2c.write(buf)	
        self.i2c.stop()
````

I am new to micropython and its usage but it seems to me that this latest version is assuming a newer or different  'core/kernel' (or whatever the pre installed image is called ) version.

**Comment by RobertK66** [comment]
Closing this because the workaround is good enough to get my hardware tests done. Only wrote this issue to document for others 😉 .

**Comment by UnexpectedMaker** [comment]
Hi @RobertK66 
You are correct, I accidentally had a newer ssd1306 library included :(
I've replaced it with the correct library now, so no workarounds are required.
Thanks for letting me know
Seon.

**Comment by noderat** [comment]
I'm still getting failures on this even after the revert:

```
Traceback (most recent call last):
  File "main.py", line 298, in <module>
  File "ssd1306.py", line 99, in __init__
  File "ssd1306.py", line 36, in __init__
  File "ssd1306.py", line 61, in init_display
  File "ssd1306.py", line 104, in write_cmd
OSError: [Errno 110] ETIMEDOUT
```

**Comment by konimaru** [comment]
@noderat FWIW, the current head of git works for me although I'm on 1.11 now.

Can you check what devices you can see on the bus? Just to make sure it's not a connection issue.
```
from machine import I2C
i2c = I2C(scl=Pin(22), sda=Pin(21))
i2c.scan()
```

**Comment by UnexpectedMaker** [comment]
@noderat - That doesn't look good. As @konimaru suggests, can you do a scan to make sure the screen can be found? It should find the OLED and IMU on the I2C bus.

The TinyPICO shipped with a MicroPython hybrid that was 1.10 + a bunch of ESP32 fixes and improvements from 1.11. The latest 1.11 is pretty stable, so if the I2C scan sees the screen and the IMU, maybe look at flashing your TinyPICO with the latest MP?

**Comment by noderat** [comment]
I upgraded to 1.11 shortly after receiving my kit, but it doesn't look like it's picking up the display:

```
MicroPython v1.11-187-g00e7fe8ab on 2019-08-01; ESP32 module with ESP32
Type "help()" for more information.
>>> from machine import I2C, Pin
>>> i2c = I2C(scl=Pin(22), sda=Pin(21))
>>> i2c.scan()
[]
```

**Comment by konimaru** [comment]
@noderat: does pressing RESET on the game shield have any effect on the TinyPICO (when plugged in)?

**Comment by UnexpectedMaker** [comment]
@noderat Are you on the Unexpected Maker discord server?
https://discord.gg/wkT3pd2

If not, join and PM me please so we can discuss next steps.
