### ISSUE TITLE
UART causes a crash

### ISSUE THREAD

**Issue by teuler** [tinypico/tinypico-micropython#4]
with tinypico-idf3-20200110-v1.12-45-gbfbd94401.bin (or with the idf4 version), UARTs cannot be used:

from machine import UART
u = UART(1)
=> crash, reboot loop (when in program code)

From REPL:

>>> MPY: soft reboot
>>> MicroPython v1.12 on 2019-12-20; TinyPICO with ESP32-PICO-D4
>>> Type "help()" for more information.
>>> from machine import UART
>>> u = UART(1)
I (36410) uart: ALREADY NULL
>>>

**Comment by UnexpectedMaker** [comment]
That's correct behaviour on the ESP32-PICO-D4 as the default pins for UART 2 and 3 that Espressif chose are not available on the D4 - They are instead reserved for Flash and RAM.

You need to specify the pins you want to use in the constructor (not afterwards) and then it works correctly.

**Comment by teuler** [comment]
I didn't know that - it works now!
Thanks for the prompt reply!
