### ISSUE TITLE
micropython-tinypico-1.12.bin contains limited TinyPICO Helper

### ISSUE THREAD

**Issue by flashypepo** [tinypico/tinypico-micropython#5]
The frozen TinyPICO Helper (tinypico.py) in the firmware v1.12.bin does not contain the helper functions get_internal_temp_F() and get_internal_temp_C(). I did not test the firmware v1.11.bin.

**Comment by UnexpectedMaker** [comment]
Internal temperature functionality has been depreciated in the silicon by Espressif, so it's been removed from the helpers for MP and Arduino.

Seems I updated my tinypico.com website examples, but forgot to update the ones here, sorry, I'll get onto that today.

**Comment by flashypepo** [comment]
okay, thanks.
'deprecated in the silicon by Espressif' do you mean for the newer ESP32 chips? 
When I use the Python code from the tinypython.py, my TinyPico still prints the internal temperature.

**Comment by UnexpectedMaker** [comment]
A lot of their ESP32 silicon has had it removed for a while now. They have about a dozen different chips in the ESP32 range. Right now it only works own the TinyPICO (PICO-D4) if you have WiFi active, and therefore the results you get are not reliable.

**Comment by flashypepo** [comment]
Ok, thanks for the advice. Should I close the issue, or will you do it after done the updates?

**Comment by UnexpectedMaker** [comment]
Yup, that's now been updated! Cheers :)
