### ISSUE TITLE
tinypico.py confilcts with the tinypico module found in tinypico-20210902-v1.17.bin

### ISSUE THREAD

**Issue by beetlegigg** [tinypico/tinypico-micropython#8]

**Comment by UnexpectedMaker** [comment]
Correct - you don't copy that to your board, it's included in the firmware.
I provide the code so people can see it to understand how to use it.

**Comment by UnexpectedMaker** [comment]
Whoops, hit the wrong button!

**Comment by beetlegigg** [comment]
if I dont copy the tinypico.py file then I get
Traceback (most recent call last):
  File "<stdin>", line 63, in <module>
  File "<stdin>", line 45, in print_temp
AttributeError: 'module' object has no attribute ‘get_internal_temp_F'

However I copied the tinypico.py file and renamed it tinypico_helper.py and changed the import in the main file and then it all works ok.
rgs,
BG

**Comment by UnexpectedMaker** [comment]
Correct, `get_internal_temp` has been removed as it doesn't work anymore. Espressif disabled the internal temp sensor in the PICO-D4.

So use the built in one and don't use that function as it wont give you usable results.

I show it's been depreciated here in the code:
https://github.com/tinypico/tinypico-micropython/tree/master/tinypico-helper

**Comment by beetlegigg** [comment]
ok, thanks for the info
rgs
BG

**Comment by UnexpectedMaker** [comment]
nps, closing this off.
